default_events:
- pull_request

default_permissions:
  checks: write
  metadata: read
  pull_requests: read
  members: read
  single_file: read

name: Review from code owners

url: https://github.com/keik/require-review-from-code-owners

description: Require review from code owners.

# Set to true when your GitHub App is available to the public or false when it is only accessible to the owner of the app.
# Default: true
# public: false
