default_events:
- pull_request
- pull_request_review

default_permissions:
  checks: write
  metadata: read
  pull_requests: read
  members: read
  single_file: read

single_file_name: .github/CODEOWNERS

name: Code Owners review

url: https://github.com/keik/github-app-code-owners-review

description: Require review from code owners.

# Set to true when your GitHub App is available to the public or false when it is only accessible to the owner of the app.
# Default: true
# public: false
